### ISSUE TITLE
Multiple Trains going to one requesting train stop.

### ISSUE THREAD

**Issue by Opiboble** [Yousei9/Factorio-LogisticTrainNetwork#10]
Hello,

First off - love the mod, it is helping manage my massive train network very well. However I have ran into a small issue. Not a bug necessarily, but a change in function, or an additional option.

Here is the problem: To minimize the number of train stops I need at a remote factory I combine Providers and Requester. Now the problem is when I add a stop that -10,000 of an item, the providers of said items get inundated with several trains (I got 12 depots, with 12 trains), and end up clogging the main line in the area.

To resolve this I would love to see a circuit condition to dictate how many trains can queue up at a provider, or requester station. Thus preventing trains from going to the station if it already has a train planning on going to it. 

Again, thanks for the awesome mod, and if you need an image of the issue I am running into let me know.

**Comment by Yousei9** [comment]
I'm happy someone else than myself is using Provider/Requester in one station.

In case you are using the design I posted on the forum or something similar please note loading times are poor compared to stations using 12 stack inserters for loading/unloading.
I only use these to deliver supplies (repair packs, ammo, items needed to build outposts), resources normally going on a bus are better delivered through dedicated loading/unloading stations with 12 (stack) inserter/wagon.

10k should easily fit in a single train. Raising min delivery size or using decider combinators to only let negative values below a full train pass reduces trains sent to a minimum.

Your request is easy to implement as LTN already picks providers with least active deliveries first. The way I understood your problem, that parameter would only combat symptoms while your problem is either station throughput or train utilization, or both.

**Comment by Opiboble** [comment]
I have set most of my stations up that way, where a single train can do the order request, the problem is my friends who also play on the server and don't set things up that way.

Essentially they request 20k iron plates to deliver to a remote factory, but they leave the min. request amount blank so it uses default. Thus 4 trains rush off to the closest iron smelting factory to pick up plates. Now sadly I didn't think ahead when I designed my rail stops to have holding areas for multiple trains at once, so they clog up the main line and sometimes creates a deadlock :/

Now I generally go about fixing this problem by adjusting the values at the requesting stop, but it can be a pain in the ass sometimes depending on how much my friends built while I was asleep. So I am basically just asking for a quick fix from you, lol. By having a default value of "Don't allow another train to go to that station if one is already scheduled" that you can then adjust higher using circuits to "You can send 2 trains to do that station, but no more" would make my Factorio time more about building new things, and less fixing the errors of my friends... Otherwise I have to find new friends, lol.

**Comment by Yousei9** [comment]
I'm firmly against promoting lazy design. Instead LTN, just like the base game, aims to provide tools needed to overcome most problems through clever designs.
Factorio would get boring very fast if you had magic buildings you can just slap down anywhere and they just work perfectly. (10s to first rocket with Creative Mode)

Any deadlock can be easily fixed with proper signaling. You can pm me on the forum if you want me to look over your junction designs.

If you can't talk to friends about problems you have with fixing their broken designs you probably should find real friends.
PS: You could always set the default min_delivery_size to reasonable larger size like 10k+ or enforce setting min delivery size by setting the default unreasonable high.

**Comment by Yousei9** [comment]
Implemented in 0.10.0.
