### ISSUE TITLE
Constant signal when train is ready for loading

### ISSUE THREAD

**Issue by Alxandr** [Yousei9/Factorio-LogisticTrainNetwork#26]
I just made a rather fancy station by using a bunch of combinators that I'm pretty happy with. However, it uses the fact that the lamp stops being yellow to reset it's counter, which is not optimal. So I was wondering, could you have a "train at station" signal in the output? Not just the composition, but a constant signal that's equal for all trains?

**Comment by Yousei9** [comment]
Simply aggregate all locomotive types into base locomotive:
Encoded positions of LocomotiveA + Encoded positions of LocomotiveB = Encoded positions of Locomotive 

If you go all fancy with combinators anyway, 1 arithmetic  for every additional 2 locomotive types shouldn't make a difference.

**Comment by Alxandr** [comment]
Hmm, fair point. I still think it would be nice to have it as a built in signal though

**Comment by Yousei9** [comment]
There's no need to spam signals containing practically the same information.

**Comment by Alxandr** [comment]
Well, yes there is a point, because of mods all my trainstops now need an extra 3 combinations. That's more things that go wrong, and more things to debug

**Comment by Yousei9** [comment]
What mods do you to have 6-7 different types of locomotives?
Even with Yuoki trains i never used more than 2-3 types.

**Comment by Alxandr** [comment]
Yeah, I was thinking the same thing. I will likely only use 2 wagon types so I can encode their positions the same everywhere.

**Comment by Xasin** [comment]
I think a couple of additions to the output system would be nice, yeah! 

I myself have just constructed a small logic using four Combinators and one Decider.
Why? 

- It generates one pulse of all items on the train when said train arrives.
- This is then looped in a single combinator, allowing me to count down/up on it as the inserters work (so that basically I can always deliver or pick up the correct amount of items)
- Additionally, when the train leaves (detected by *All Signals == 0*) that loop is cleared, should some items not have been available.

That whole thing could be simplified a bit. I suggest two methods:
- Pulse the output of the logistics train station once, to allow for easier "loop"-type counters. (Would break things though, I know)
- Change the output behavior of the lamp so that it does not reflect the value you want to add/remove from the train, but the *total* amount of items on the train you want to have *after* loading/unloading. That way, using a single combinator the user can subtract the current train's loaded items, and thusly get how much is left to load/unload. Might also break things, but not in such a severe way ... I hope.

**Comment by Yousei9** [comment]
With 0.15 you can get away with using only 1 combinator for loading and unloading.
Note: LTN assumes trains are empty at the start. Having residue will mess with train capacity calculation.

**loading:** 
Station (read train inventory) hooked into arithmetic combinator each*-1=each
merge the signal with yellow combinator
feed into filter inserters

**unloading:** (doesn't cycle through items though)
hook yellow combinator into arithmetic combinator each*-1=each
feed into filter inserters

**unloading everything:**
use unfiltered inserters activated by their respective train composition signals.
Not going to describe how binary decoding work here, read XKnight's thread or the posts on LTN about it.


I haven't changed the output to show train contents expected after un-loading since it'd break every station for everyone. It'd also be kind of confusing if the output shows only what should not be unloaded in case of residue.
e.g. iron/copper mine incorrectly loaded some copper
at the unloading station the station would read 1950 iron, 12 copper and the output would show 12 copper and no iron.

**Comment by Alxandr** [comment]
I'm actually trying to make a combinator mod for this and another scenario I encountered in another mod. But it'll be a while (if ever) cause I've never modded factorio before. But yeah, I'll add pulse-generator to the list of generators on my planned list (forward all signals only a single tick).

**Comment by Yousei9** [comment]
You can test the toggle in the preview for 1.2.4 i just uploaded. https://github.com/Yousei9/Factorio-LogisticTrainNetwork/tree/1.2.4

**Comment by Xasin** [comment]
@Alxandr 
If you can make that happen, send me a note - I'd kill for that. 
Also, maybe add a "signal forwarder"? Basically just a device cheaper than a combinator that doesn't do anything apart from ... Well, forwarding the signal?
I have a couple of arrangements where I have to place a combinator just to either delay a signal by a tick, or to prevent, say, a inserter with "Send hand contents" on that needs to receive from a network it shouldn't influence.

Also, thanks Yousei! 
I'll give it a try over the next bit. Should make loading/unloading a bit easier, at least for me :+1:

**Comment by Yousei9** [comment]
I don't want to further derail this, but can't ignore it either.
Pulse generator and signal delay can be done very cheap. Lua needs to do a lot more complex things to warrant the overhead it produces. Especially since these things need to run on_tick.
For more information look in the combinator contraption subforum.

If you make a station able to load and unload let me know. My current version is a combinator heavy monster.

**Comment by Xasin** [comment]
I was already able to produce a functional loading/unloading system for me, using the new output mode you implemented. Thanks for that! 

Basically, the only thing I use is a single combinator that multiplies the current train contents with -1. Then, the "expected train contents after loading" signals are added to that.
The resulting signal can be fed into (stack) (filter) inserters, which are activated when their respective signal is >0
Additionally, the stack inserters can be configured to only activate when the signal is >12, >24, etc.
Then, the last inserter (with a condititon >0) can be set to "set stack size" with the same signal - and tada, you get a system that always loads the right amount, with just one comparator.

For unloading I just connect the comparator differently, so that it multiplies the "train contents after loading" signal with -1. That way you can use exactly the same technique to unload the train to a precise amount.

I think it works great!

**Comment by Yousei9** [comment]
When it comes to unloading and loading at one station it still gets complicated, though I needed only 11 instead of 22 combinators for the redesign.
https://forums.factorio.com/viewtopic.php?f=94&t=36976&start=600#p273279

**Comment by Xasin** [comment]
Well, I suppose I didn't take into account more complex hybrid systems that can balance a train item number ... 
But it's a convenient coincidence that this also works better for other stations.

Thanks a lot for adding this! It works great for me :+1:
